app = "globalconfig-dht"

# make doesn't pass SIGINT?
kill_signal = "SIGKILL"
kill_timeout = 5

[experimental]
  entrypoint = ["./run"]
  cmd = []

[[services]]
  internal_port = 42069
  protocol = "tcp"

  [[services.tcp_checks]]
    # Wait for first publish
    grace_period = "5m"
    # How do we handle down time during DHT publishes?
    interval = "60s"
    timeout = "5m"

[[services]]
  internal_port = 42069
  protocol = "udp"
