app = "globalconfig-dht"

# make doesn't pass SIGINT?
kill_signal = "SIGKILL"
kill_timeout = 5

[experimental]
  # TODO: Write a script that does this in a loop instead so we can reuse VMs
  entrypoint = ["timeout", "3600", "make"]

[[services]]
  internal_port = 42069
  protocol = "tcp"

  [[services.tcp_checks]]
    grace_period = "1m"
    interval = "15s"
    timeout = "2s"

[[services]]
  internal_port = 42069
  protocol = "udp"
